spring:
  application:
    name: SaharaTaskRadiationProject

  datasource:
    url: jdbc:postgresql://localhost:5432/taskradiation
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true

server:
  port: 8080

